### ISSUE TITLE
Improve Build Instructions on Windows

### ISSUE THREAD

**Issue by bjjones** [kainino0x/deqp-web-harness#6]
We should be able to build this repository on Windows, however I've had issues following the instructions in the README.

The README states: 

> On Windows, it currently may be necessary to make a small patch to zlib in order to build the project: In deqp\external\zlib\src\gzguts.h, add #include <unistd.h>.

This is confusing to me, because unistd.h is not a Windows library, and adding this will result in more errors. 

The solution here could be using something like Cygwin, or getting emcmake to correctly configure for building with Visual Studio. I have not yet been successful with the latter - but I'm also not an experienced emscripten user.

**Comment by kainino0x** [comment]
I haven't actually tried to build on Windows myself - though I really should. I got this feedback from Yang (I'll forward you the email).

Emscripten should always behave like a Unix target platform - regardless of the host system you're compiling on. So I think unistd.h should be available.

**Comment by bjjones** [comment]
So I spent more time on this - and I got it building. I was able to get past the Zlib part I mentioned using the direction provided - apologies for the false alarm there.
